apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: maintenance
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: maintenance
      sslmode: disable
      postgresVersion: 16
      timescaledb: false
    editable: false